# Generated by Django 3.0.7 on 2021-07-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210710_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='is_follow',
        ),
    ]
